name: "Test GitHub Token Injection"
on:    
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Action
        id: get-token
        uses: amagimedia/git-token-action@main
        with:            
            github-app-id: ${{ secrets.APP_ID }}
            github-installation-id: ${{ secrets.INSTALLATION_ID }}
            github-pvt-key: ${{ secrets.PVT_KEY }}

      - name: Use the Injected Token
        run: |
          echo "Using the injected token..."
          curl -H "Authorization: Bearer $AMAGI_GITHUB_TOKEN" https://api.github.com/user